#!/bin/bash

# Obtenir le nom de la branche actuelle
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Définir le regex pour la nomenclature autorisée
regex="^(feature|bugfix|hotfix|release)\/[a-z0-9_\-]+$"

# Exclure les branches "main" et "develop"
if [[ "$branch_name" == "main" || "$branch_name" == "develop" ]]; then
    echo "✅ La branche '$branch_name' est une branche autorisée et ne nécessite pas de vérification."
    echo "Si ce message s'affiche, vérifier le format de la branch ou le format du commit"
    echo "Format de la branch -> feature/ajout-login"
    echo "Format du commit -> [feat|fix|docs|style|refactor|test|chore]: message --- exemple: [feat: ajout login], faite bien attention à l'espace entre le type le \":\" et le message"
    exit 0
fi

# Vérifier si le nom de branche respecte la convention
if [[ ! $branch_name =~ $regex ]]; then
    echo "❌ Erreur : Le nom de branche '$branch_name' ne respecte pas la convention."
    echo "✅ Utilisez un format valide, par exemple :"
    echo "   - feature/ajout-login"
    echo "   - bugfix/correction-affichage"
    echo "   - hotfix/urgence-probleme"
    echo "   - release/v1.0.0"
    exit 1
else
    echo "✅ Le nom de branche '$branch_name' respecte la convention."
fi